### PR TITLE
Integrating Sym with Core: Network Architecture Layers

### PR DESCRIPTION
**Pull request by mnabian**
# Modulus Pull Request

## Description

Closes https://github.com/NVIDIA/modulus-sym/issues/64

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Comment by loliverhennigh** [comment]
We can pull over `sym.models.activation` to core as well but maybe we can make that a separate PR and leave it for the future unless you think its easy to do now.

**Review by loliverhennigh — APPROVED** [review]

**Comment by mnabian** [comment]
> We can pull over `sym.models.activation` to core as well but maybe we can make that a separate PR and leave it for the future unless you think its easy to do now.

@loliverhennigh it requires some refactoring, as we already have some activations in core: https://github.com/NVIDIA/modulus/blob/main/modulus/models/layers/activations.py
Let us track this in a separate PR.

**Review by ktangsali — APPROVED** [review]

**Pull request merged**
