### PR TITLE
[FEA] Packaging improvements

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
This PR adds/improves the following:

- Adds a devcontainer
- Relaxes dependencies and updates cleans up the order
- Speeds up the cuda extension build from ~2m24s to ~46s (3x speed improvement)

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Review by Alexey-Kamenev — APPROVED** [review]
> Speeds up the cuda extension build from ~2m24s to ~46s (3x speed improvement)

You are a magician, Kaustubh!

**Comment by ktangsali** [comment]
> > Speeds up the cuda extension build from ~2m24s to ~46s (3x speed improvement)
> 
> You are a magician, Kaustubh!

Would not have been possible without your support 🙂

**Pull request merged**
