### PR TITLE
Update Dockerfile to add --no-build-isolation flag

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
add `--no-build-isolation` flag to prevent reinstall of pytorch

Verified the update by doing a local build and running pytests

```
======================================================================= 173 passed, 104 warnings in 111.14s (0:01:51) ========================================================================
```

## Checklist

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Comment by ktangsali** [comment]
Before:

```
root@c1deb367d50d:/examples/ktangsali/modulus-sym# pip install --no-cache-dir . --no-deps
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Processing /examples/ktangsali/modulus-sym
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-build-env-t9obe48q/overlay/local/lib/python3.10/dist-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-t9obe48q/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-t9obe48q/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-t9obe48q/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 45, in <module>
        File "<string>", line 25, in cuda_extension
      TypeError: float() argument must be a string or a real number, not 'NoneType'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python -m pip install --upgrade pip
```

After:

```
root@c1deb367d50d:/examples/ktangsali/modulus-sym# pip install --no-cache-dir . --no-deps --no-build-isolation
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Processing /examples/ktangsali/modulus-sym
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: nvidia-modulus.sym
  Building wheel for nvidia-modulus.sym (pyproject.toml) ... done
  Created wheel for nvidia-modulus.sym: filename=nvidia_modulus.sym-1.7.0a0-cp310-cp310-linux_aarch64.whl size=581142 sha256=f850fe886bfb57839ed7a3ef91f2c3626379c7167967d92bc28c3f738a7ec9ef
  Stored in directory: /tmp/pip-ephem-wheel-cache-062b1wy3/wheels/2c/a6/68/963e4d092515e07d3c991dc3df081d294b08b6838a54d9e3b6
Successfully built nvidia-modulus.sym
Installing collected packages: nvidia-modulus.sym
Successfully installed nvidia-modulus.sym-1.7.0a0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python -m pip install --upgrade pip
```

**Review by Alexey-Kamenev — APPROVED** [review]

**Pull request merged**
