### PR TITLE
Fixing FusedSiLU tests

### PR DESCRIPTION
**Pull request by akshaysubr**
# Modulus Pull Request

## Description
Fixing test to also filter cuLaunchKernel in addition to cudaLaunchKernel

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is
up to date with these changes.

## Dependencies

None

### CODE REVIEW

**Review by ktangsali — APPROVED** [review]
Thanks! Looking good

**Comment by mnabian** [comment]
@akshaysubr please update the changelog

**Review by mnabian — APPROVED** [review]

**Comment by akshaysubr** [comment]
@mnabian Updated the changelog

**Pull request merged**
