### PR TITLE
Updating Norne branch

### PR DESCRIPTION
**Pull request by clementetienam**
# Modulus Pull Request

## Description
- Updated the architecture of CCR from a polynomial regressor expert to an XGboost regressor expert
- Implementation for multi-GPU run in the forward and inverse problem
- Improved computation in Jeffrey's divergence for the loss criteria during the inverse problem
- Improved parallel plotting for the pressure, water saturation and gas saturation movies
- improved selection of petrophysical priors during the inverse problem

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Comment by clementetienam** [comment]
Updating some necessary files

**Comment by clementetienam** [comment]
Updating the Readme.MD

**Review by ktangsali — APPROVED** [review]
Changes look good to me!

**Pull request merged**
