### PR TITLE
README updates 02152024

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
- Adds hyperlink to each example entry in master readme
- Adds links to Core's examples

Closes: https://github.com/NVIDIA/modulus-sym/issues/109

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Review by ram-cherukuri — APPROVED** [review]
Looks good.

**Comment by ktangsali** [comment]
This PR will also Closes: https://github.com/NVIDIA/modulus-sym/issues/109

**Pull request merged**
