### PR TITLE
Add inference analysis for the turbulence super resolution example

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Adds inference analysis for the turbulent super resolution example. 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Review by akshaysubr — COMMENTED** [review]
This looks quite good to me. I have two main comments:

1. The first energy spectrum plot is super noisy. Is that not doing any averaging? Also, what is the difference compared to the next energy spectrum plot?
2. For the continuity residual, would be better to plot a histogram of the first invariant of the velocity gradient tensor, P, similar to how you compute Q and R.

**Comment by ktangsali** [comment]
> This looks quite good to me. I have two main comments:
> 
> 1. The first energy spectrum plot is super noisy. Is that not doing any averaging? Also, what is the difference compared to the next energy spectrum plot?
> 2. For the continuity residual, would be better to plot a histogram of the first invariant of the velocity gradient tensor, P, similar to how you compute Q and R.

Thanks Akshay, I have addressed your comments. Added plots for `P` invariant and also cleaned up the spectrum plots. 

Please take a look!

**Review by akshaysubr — APPROVED** [review]
Looks good!

**Pull request merged**
